INSERT INTO candidates (name, experience_years, skills) VALUES
('Alfred Marvin', 12, 'Safety Compliance, Waste Management, Lean Manufacturing'),
('Mable Mayert', 8, 'Sustainability Planning, Safety Compliance, Team Leadership'),
('Antonina Cassin', 2, 'Lean Manufacturing, Team Leadership, Sustainability Planning'),
('Wendy Rutherford', 10, 'Sustainability Planning, Waste Management, Safety Compliance'),
('Saul Gerhold', 13, 'Team Leadership, Waste Management, Safety Compliance'),
('Jessie Roob', 7, 'Lean Manufacturing, Sustainability Planning, Team Leadership'),
('Nat Reichert', 7, 'Sustainability Planning, Team Leadership, Waste Management'),
('Lila Batz', 12, 'Sustainability Planning, Lean Manufacturing, Safety Compliance'),
('Wilber Schroeder', 2, 'Team Leadership, Safety Compliance, Waste Management'),
('Gia Wisoky', 10, 'Safety Compliance, Lean Manufacturing, Waste Management'),
('Trevor Bednar', 4, 'Team Leadership, Safety Compliance, Sustainability Planning'),
('Abagail Lockman', 2, 'Team Leadership, Safety Compliance, Lean Manufacturing'),
('Jamie Carroll', 9, 'Team Leadership, Lean Manufacturing, Safety Compliance'),
('Kristoffer Rolfson', 9, 'Sustainability Planning, Waste Management, Team Leadership'),
('Jan Spencer', 5, 'Sustainability Planning, Safety Compliance, Lean Manufacturing'),
('Johnathan Hermiston', 11, 'Team Leadership, Waste Management, Safety Compliance'),
('Ora Frami-Larson IV', 13, 'Lean Manufacturing, Waste Management, Team Leadership'),
('Manuela Buckridge', 8, 'Team Leadership, Safety Compliance, Sustainability Planning'),
('Joshuah Weber', 13, 'Lean Manufacturing, Team Leadership, Waste Management'),
('Jammie Crooks', 15, 'Waste Management, Lean Manufacturing, Team Leadership'),
('Danielle Homenick', 7, 'Sustainability Planning, Safety Compliance, Team Leadership'),
('Coy Langosh', 11, 'Waste Management, Sustainability Planning, Safety Compliance'),
('Traci Grant', 14, 'Waste Management, Team Leadership, Lean Manufacturing'),
('Glenn Schmitt', 10, 'Lean Manufacturing, Waste Management, Sustainability Planning'),
('Rodrick Runolfsson', 9, 'Sustainability Planning, Lean Manufacturing, Team Leadership'),
('Marianne Mante', 13, 'Lean Manufacturing, Waste Management, Sustainability Planning'),
('Aiyana Morar', 9, 'Team Leadership, Safety Compliance, Sustainability Planning'),
('Ava Mueller V', 10, 'Team Leadership, Safety Compliance, Lean Manufacturing'),
('Constantin Jerde', 9, 'Team Leadership, Safety Compliance, Waste Management'),
('Isabel Hilpert', 10, 'Lean Manufacturing, Sustainability Planning, Waste Management'),
('Sherman Kassulke', 12, 'Sustainability Planning, Lean Manufacturing, Safety Compliance'),
('Guadalupe Cruickshank', 7, 'Sustainability Planning, Safety Compliance, Team Leadership'),
('Delbert Pacocha PhD', 6, 'Sustainability Planning, Safety Compliance, Lean Manufacturing'),
('Dr. Leslie Klein', 5, 'Safety Compliance, Team Leadership, Lean Manufacturing'),
('Guy Ritchie', 14, 'Sustainability Planning, Lean Manufacturing, Waste Management'),
('Bridget Little', 10, 'Waste Management, Safety Compliance, Lean Manufacturing'),
('Dr. Willa Pouros', 6, 'Team Leadership, Waste Management, Sustainability Planning'),
('Zena Strosin PhD', 5, 'Waste Management, Safety Compliance, Lean Manufacturing'),
('Marcus Boyle', 2, 'Waste Management, Sustainability Planning, Team Leadership'),
('Mr. Johnnie Blanda', 11, 'Lean Manufacturing, Waste Management, Team Leadership');
